### PR TITLE
removed colon from file names and refactored references

### LINKED ISSUE #210: Cannot clone on Windows
git clone unable to create file server/mongorestore/data/_Join:mySchedule:_User.bson: Invalid argument

A colon is an invalid character for a Windows file name.

### PR DESCRIPTION
**Pull request by saranshkataria**
Fixes #210

### CODE REVIEW

**Review by caabernathy — COMMENTED** [review]
See my comments in the original issue filed. I'm thinking that renaming the class name would cause an issue. Please verify that.

**Review by tmd8886 — APPROVED** [review]

**Review by tmd8886 — CHANGES_REQUESTED** [review]
Facebook basic version download

**Comment by tmd8886** [comment]
Facebook basic version download

**Review by GopalMamtani — APPROVED** [review]

**Comment by wo4chenkewen** [comment]
so this issue is closed? but why have this problem again in my windows 10 platform while cloning this project to my local file system.

**Comment by wo4chenkewen** [comment]
image
so what should I do to avoid this annoying issue.

**Pull request closed without merging**
