### PR TITLE
Update jest-cli to 12.1 - fixing tests

### PR DESCRIPTION
**Pull request by tonyxiao**
Fixes issue https://github.com/fbsamples/f8app/issues/52

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by tonyxiao** [comment]
@facebook-github-bot-4 Signed. :)

**Comment by facebook-github-bot-3** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by frantic** [comment]
Would you mind running `npm shrinkwrap --dev`? We use it here to make sure the installation process is as reproducible as possible

**Comment by tonyxiao** [comment]
Hmm I'm actually having trouble running `npm shrinkwrap --dev` on a fresh clone of `f8app`. Got ideas?

```
Tony:f8app (master)$ npm shrinkwrap --dev
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/Tony/.nvm/versions/node/v6.0.0/bin/node" "/Users/Tony/.nvm/versions/node/v6.0.0/bin/npm" "shrinkwrap" "--dev"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! invalid: have react-native-fbsdk@0.1.0-alpha.1 (expected: github:facebook/react-native-fbsdk#0.1.0-alpha.1) /Users/Tony/Code/tonyxiao/f8app/node_modules/react-native-fbsdk
npm ERR! invalid: have react-native-push-notification@1.0.2 (expected: github:frantic/react-native-push-notification#7142da7) /Users/Tony/Code/tonyxiao/f8app/node_modules/react-native-push-notification
npm ERR! invalid: have react-native-share@1.0.5 (expected: github:frantic/react-native-share#674df947b3) /Users/Tony/Code/tonyxiao/f8app/node_modules/react-native-share
npm ERR! extraneous: react-native-fbsdk@0.1.0-alpha.1 /Users/Tony/Code/tonyxiao/f8app/node_modules/react-native-fbsdk
npm ERR! extraneous: react-native-push-notification@1.0.2 /Users/Tony/Code/tonyxiao/f8app/node_modules/react-native-push-notification
npm ERR! extraneous: react-native-share@1.0.5 /Users/Tony/Code/tonyxiao/f8app/node_modules/react-native-share
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Tony/Code/tonyxiao/f8app/npm-debug.log
```

**Comment by tonyxiao** [comment]
@frantic

**Pull request closed without merging**
