### PR TITLE
Upgrade to react-native and fix the react-native-fbsdk problem in iOS

### PR DESCRIPTION
**Pull request by zhouhao27**
- Upgrade react-native to 0.30.0
- Fix the iOS problem for react-native-fbsdk by upgrade to latest version. The error message is:  `No podspec found for `react-native-fbsdk``
- Replace `StatusBarIOS` to `StatusBar`
- Upgrade parse to latest version
- Upgrade react-native-share to latest version

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-6** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by zhouhao27** [comment]
What should I do to merge it to main branch? Thanks.

**Comment by frantic** [comment]
Looks awesome, thank you! Please remove VSCode-generated files from this PR.

**Comment by zhouhao27** [comment]
Removed the vscode files already.

**Comment by frantic** [comment]
@zhouhao27 you have to `git rm .vscode`, adding `.vscode` to `.gitignore` doesn't do anything if the files have already been committed.

**Comment by zhouhao27** [comment]
@frantic done

**Pull request closed without merging**
